### ISSUE TITLE
Interest in automating cert grabbing and renewal?

### ISSUE THREAD

**Issue by aaomidi** [signalapp/Signal-TLS-Proxy#1]
It seems like we could automate the certificates being created and renewed rather than expecting people to run them. Even using another webserver like https://doc.traefik.io/traefik/https/acme/ could just get this for free.

**Comment by dunglas** [comment]
Another alternative is using Caddy server (https://caddyserver.com/), which natively manage Let's Encrypt certificates too and has other nice features such as the ability to fallback to ZeroSSL if Let's Encrypt is unavailable for some reason (downtime, blocked...).

**Comment by ViViDboarder** [comment]
Maybe I'm missing something, but it does look like the current configuration will auto-renew: https://github.com/signalapp/Signal-TLS-Proxy/blob/master/docker-compose.yml#L26

**Comment by ViViDboarder** [comment]
Oh, and on using Caddy for this, here's a relevant comment by mholt on the HN discussion thread: https://news.ycombinator.com/item?id=26027258

**Comment by hillbicks** [comment]
I already mentioned it in the another issue, but this topic seems to be more fitting:

the certbot renewal interval is way too short in my opinion. the certs are valid for 90 days, so attempting to renew every 12 hours is really not needed. depending on the amount of people spinning up servers, this could increase the load on the letsencrypt servers.

from the certbot documentation:
`Let’s Encrypt CA issues short-lived certificates (90 days). Make sure you renew the certificates at least once in 3 months.`

**Comment by moxie0** [comment]
This should already auto-renew, thanks!
