### ISSUE TITLE
Use path to mitigate domain name block

### ISSUE THREAD

**Issue by 0xe1d4b2a9** [signalapp/Signal-TLS-Proxy#7]
Domain name is sent in plaintext in the TLS channel (unless encrypted SNI enabled), allowing censors to block Signal relays according to SNI. 

Using a complicated path in addition to domain name mitigates this kind of attack. 

Example: `https://my.domain/my-signal-relay-x7KrPcOeGq2AxqTx` will be much harder to detect and block than `https://my.domain/`, especially when a "normal"-looking website is hosted on `my.domain`. Anyone hosting a personal website could do this and fight against censorship.

**Comment by DuckSoft** [comment]
You may also be interested: https://github.com/signalapp/Signal-TLS-Proxy/issues/3#issuecomment-773497762

**Comment by 0xe1d4b2a9** [comment]
> This repository is actually a TLS in TLS proxy, so cleartext SNI is not leaked.

If I am not mistaken, no, `*.signal.org` are not leaked, but `my.domain` running the proxy is leaked.

**Comment by moxie0** [comment]
That's by design. The idea is that it structured as a normal TLS connection to a normal site, with a normal SNI. The SNI for the "real" TLS connection is not visible. I'm not sure what a path would do, that's a part of an an HTTP request not a TLS packet.
